=== DHadzic/XML-VS/src/main/resources/data/schemas/CoverLetter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://localhost:8080/CoverLetter" xmlns:u="http://localhost:8080/CoverLetter">

    <xs:element name="CoverLetter">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="AuthorData"/>
                <xs:element name="Content"/>
            </xs:sequence>
            <xs:attribute name="paperId" type="xs:string"/>
            <xs:attribute name="paperTitle" type="xs:string"/>
            <xs:attribute name="commitDate" type="xs:date"/>
            <xs:attribute name="manuscriptTitle" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="AuthorData">
        <xs:sequence>
            <xs:element name="authorsName" type="xs:string"/>
            <xs:element name="authorsEmail" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="authorsPhone" type="xs:string" use="optional"/>
        <xs:attribute name="authorsAddress" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== DHadzic/XML-VS/generated/variable.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<CoverLetter xmlns="http://localhost:8080/CoverLetter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" paperId="1" paperTitle="Title" manuscriptTitle="Naslov poruke" xsi:schemaLocation="C:\Users\Damir\Desktop\xml_naucniradovi\xml\target\classes\data\schemas\CoverLetter.xsd">
    <AuthorData authorsPhone="0000000" authorsAddress="Adresa">
        <authorsName>Ime Prvog</authorsName>
        <authorsEmail>Email@prvog.com</authorsEmail>
    </AuthorData>
    <AuthorData authorsPhone="0000000">
        <authorsName>Ime Drugog</authorsName>
        <authorsEmail>Email@drugog.com</authorsEmail>
    </AuthorData>
    <Content>Some content of Cover letter by me</Content>
</CoverLetter>
