=== DHadzic/XML-VS/src/main/resources/data/schemas/Publication.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://foo.bar" xmlns="http://foo.bar" xmlns:t="http://foo.bar"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="TPublication">
        <xs:sequence>
            <xs:element name="basicInformations" type="t:TBasicInformation"/>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="paragraph" type="t:TParagraph"/>
            <xs:element maxOccurs="unbounded" name="reference" type="t:TReference"/>
        </xs:sequence>
        <xs:attribute name="language" type="xs:string"/>
        <xs:attribute form="unqualified" name="publicationId" type="xs:string"/>
        <xs:attribute name="status" default="reviewing">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="reviewing"/>
                    <xs:enumeration value="deleted"/>
                    <xs:enumeration value="rejected"/>
                    <xs:enumeration value="accepted"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="created" type="xs:date"/>
    </xs:complexType>
    <xs:complexType name="TReviewer">
        <xs:sequence>
            <xs:element name="reviewerUsername" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TReference">
        <xs:sequence>
            <xs:element name="authorName" type="xs:string"/>
            <xs:element name="paperTitle" type="xs:string"/>
            <xs:element name="year" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name="citationId" type="xs:integer" use="required"/>
    </xs:complexType>
    <xs:complexType name="TBasicInformation">
        <xs:sequence>
            <xs:element maxOccurs="1" name="title" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="authors" type="TAuthor"/>
            <xs:element name="reviewers" type="t:TReviewer"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="keywords" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAuthor">
        <xs:sequence>
            <xs:sequence>
                <xs:element name="authorUsename" type="xs:string"/>
                <xs:element name="authorInstitution" type="xs:string"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TParagraph">
        <xs:sequence>
            <xs:element name="paragraphTitle" type="xs:string"/>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element maxOccurs="1" name="text" type="xs:string"/>
                <xs:element name="citation" type="t:TCitation"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TCitation">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="authorName" type="xs:string"/>
            <xs:element name="year" type="xs:positiveInteger"/>
            <xs:element name="text" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
    <xs:element name="SciencePaper" type="t:TPublication">
        <xs:key name="id">
            <xs:selector xpath="t:paragraph/t:citation"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="citationId" refer="id">
            <xs:selector xpath="t:reference"/>
            <xs:field xpath="@citationId"/>
        </xs:keyref>
        <xs:unique name="uniqueCitationId">
            <xs:selector xpath="t:paragraph/t:citation"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:unique name="uniqueRefId">
            <xs:selector xpath="t:reference"/>
            <xs:field xpath="@citationId"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== DHadzic/XML-VS/src/main/resources/data/schemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<t:SciencePaper xmlns:t="http://foo.bar"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://foo.bar file:/D:/5.godina-Master/xml%20projekat/XML-VS/src/main/resources/data/schemas/Publication.xsd" publicationId="publicationId0" created="2006-05-04">
    <t:basicInformations>
        <t:title>title0</t:title>
        <t:authors>
            <t:username>username0</t:username>
            <t:authorInstitution>authorInstitution0</t:authorInstitution>
        </t:authors>
        <t:authors>
            <t:username>username1</t:username>
            <t:authorInstitution>authorInstitution1</t:authorInstitution>
        </t:authors>
    </t:basicInformations>
    <t:paragraph>
        <t:paragraphTitle>paragraphTitle0</t:paragraphTitle>
        <t:element>
            <t:text>text0</t:text>
        </t:element>
        <t:element>
            <t:citation id="0">
                <t:authorName>authorName0</t:authorName>
                <t:authorName>authorName1</t:authorName>
                <t:year>50</t:year>
                <t:text>text1</t:text>
            </t:citation>
        </t:element>
    </t:paragraph>
    <t:paragraph>
        <t:paragraphTitle>paragraphTitle1</t:paragraphTitle>
        <t:element>
            <t:citation id="0">
                <t:authorName>authorName2</t:authorName>
                <t:authorName>authorName3</t:authorName>
                <t:year>50</t:year>
                <t:text>text2</t:text>
            </t:citation>
        </t:element>
        <t:element>
            <t:citation id="0">
                <t:authorName>authorName4</t:authorName>
                <t:authorName>authorName5</t:authorName>
                <t:year>50</t:year>
                <t:text>text3</t:text>
            </t:citation>
        </t:element>
    </t:paragraph>
    <t:reference citationId="0">
        <t:authorName>authorName6</t:authorName>
        <t:authorName>authorName7</t:authorName>
        <t:paperTitle>paperTitle0</t:paperTitle>
        <t:year>50</t:year>
        <t:url>url0</t:url>
    </t:reference>
    <t:reference citationId="0">
        <t:authorName>authorName8</t:authorName>
        <t:authorName>authorName9</t:authorName>
        <t:paperTitle>paperTitle1</t:paperTitle>
        <t:year>50</t:year>
        <t:url>url1</t:url>
    </t:reference>
</t:SciencePaper>
